### ISSUE TITLE
`isEmpty()` issues

### ISSUE THREAD

**Issue by Dobatymo** [pablocael/pynear#24]
https://github.com/pablocael/pyvptree/blob/f764e562e641d2616e2d2ddfcc404942cc6ecffa/pyvptree/include/VPTree.hpp#L43

should the second condition be `_indexEnd`? also both variables are unsigned integers which are never `-1`. I would feel better with explicit casts for `-1` everywhere (also reduced compiler warnings)

**Comment by pablocael** [comment]
Yes. Will fix in my next PR! Thank you!

**Comment by pablocael** [comment]
Fixed on #32
